config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :skills
  resources :projects
  resources :users
  resources :project_users

  root 'welcome#index'

end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :password, :password_confirmation
	has_and_belongs_to_many :skills
	has_many :project_users
  has_many :projects, through: :project_users
  has_attached_file :image, styles: { :medium => "640x" }


	validates :name,presence: true, length: { minimum: 2 }
  validates :password, presence: true, allow_nil: true
	validates_length_of :password, minimum: 6
  validates_confirmation_of :password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/
	validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
	validates_attachment :image, presence: true, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
	do_not_validate_attachment_file_type :image

	before_save :encrypt_password
	after_save :clear_password

	def encrypt_password
  	if password.present?
    	self.salt = BCrypt::Engine.generate_salt
    	self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
  	end
	end

	def clear_password
  	self.password = nil
	end

	def self.authenticate(email="", login_password="")
  	if  VALID_EMAIL_REGEX.match(email)
    	user = User.find_by_email(email)
  	end
  	if user && user.match_password(login_password)
    	return user
  	else
    return false
    end
  end

  def match_password(login_password="")
  	encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :correct_user,   only: [:show, :edit, :update]
  before_action :admin_user,     only: [:index, :destroy]

  def new
    puts "before user initialize"
    @user = User.new
    puts "after user initialize"
    @skills = Skill.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
    	redirect_to @user
    else
      flash[:error] =  @user.errors.full_messages.join(', ')
      puts "redirect on new form"
      redirect_to new_user_path
    end
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    @skills = Skill.all
  end

  def update
    @skills = Skill.all
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @array = @user.project_users.map(&:project_id)
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private
  def user_params
    params.require(:user).permit(:role, :name,:email, :password, :password_confirmation, :image, :skill_ids => [] )
  end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_form.html.erb
<% @page_title = "UserAuth" %>
<div class="">
  <h1>Please enter details:</h1>
  <%= form_for(@user) do |f| %>
    <p> Name:</br> <%= f.text_field :name%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <div class="field">
      <%= collection_check_boxes(:user, :skill_ids, @skills, :id, :skill) %>
    </div>
    <p> Profile Picture:</br> <%= f.file_field :image%></p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1> Edit Form </h1>
<%= render 'form' %>
<%= link_to 'Back', current_user %>

app/views/users/index.html.erb
<table>
  <tr>
    <th>Users</th>
    <th colspan="2"></th>
  </tr>
	<% @users.each do |user| %>
  	<tr>
    	<td><%= user.name %></td>
      <td><%= user.email%></td>
      <td><%= user.skills.map {|s| s.skill}.join(', ') %></td>
      </td>
    	<td><%= link_to "delete", user, method: :delete,data: { confirm: "You sure?" } if !user.admin?%> </td>
    </tr>
  <% end %>
</table>
<br>

<%= link_to "Back", current_user %>
</ul>

app/views/users/new.html.erb
<h1> New Form </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
      <p> <%= image_tag @user.image%> </p>
        Welcome
        <%=@user.name%>!!
      </h1>
      <p>
        <strong>Skill Name:</strong>
        <%= @user.skills.map {|c| c.skill}.join(', ') %>
      </p>
      <strong>Projects Name:</strong>
      <% @array.each do |id| %>
        <%= Project.find(id).name %>
      <% end %>
    </p>

      <h2>
      <li><%= link_to "Edit", edit_user_path %></li>
        <%= link_to "Logout", session_path(session),method: :delete,data: { confirm: 'Are you sure?' } %>
        <%= link_to "Users", users_path if @user.admin? %>
        <%= link_to "Projects", projects_path if @user.admin? %>
        <%= link_to "Skills", skills_path if @user.admin? %>
        <%= link_to "Assigned Projects", project_users_path if @user.admin? %>
      </li>
      </h2>

    </section>
  </aside>
</div>