config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :skills
  resources :projects
  resources :users
  resources :project_users

  root 'welcome#index'

end

app/models/skill.rb
class Skill < ApplicationRecord
	has_and_belongs_to_many :users
	has_and_belongs_to_many :projects
	validates :skill, length: { minimum: 2 }
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :admin_user,     only: [:new, :create,:edit,:update, :index, :destroy, :show]
  def new
  	@skill = Skill.new
  end

  def edit
    @skill = Skill.find(params[:id])

  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to new_skill_path
    else
      flash[:error] =  @skill.errors.full_messages.join(', ')
      redirect_to new_skill_path
    end
  end

  def index
    @skills = Skill.all
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      redirect_to @skill
    else
      render 'edit'
    end
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def destroy
   Skill.find(params[:id]).destroy
   flash[:success] = "Skill deleted"
   redirect_to skills_url
  end

  private
    def skill_params
      params.require(:skill).permit(:skill,:user_ids => [])
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<% @page_title = "Skill" %>
<div class="skill">
  <h1>Skill input</h1>
  <%= form_for(@skill) do |f| %>
    <p> Skill:</br> <%= f.text_field :skill%> </p>
    <%= link_to "Create new skill", {controller: 'skills', action: 'new'} %>
    <%= f.submit "Submit" %>
   <% end %>

   <% if @skill.errors.any? %>
    <ul class="Skill_Errors">
    <% for message_error in @skill.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/skills/edit.html.erb
<h1> Edit Form </h1>
<%= render 'form' %>
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<table>
  <tr>
    <th>Skills</th>


    <th colspan="2"></th>
  </tr>

  <% @skills.each do |skill| %>
    <tr>
      <td><%= skill.skill %></td>
      <td><%= link_to "Show", skill_path(skill)  %></td>
      <td><%= link_to "Edit",edit_skill_path(skill) %></td>
      <td><%= link_to 'Destroy', skill ,method: :delete,data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to "Create new skill", {controller: 'skills', action: 'new'} %>
<br>
<%= link_to "Back", current_user %>

app/views/skills/new.html.erb
<% @page_title = "Project" %>
<%= render 'form' %>
<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<% @page_title = "Skill list" %>
 <div class="Skill">
  <table>
  <tr>
    <th>Name</th>

    <th colspan="2"></th>
  </tr>
 
      <tr>
      <td><%= @skill.skill %></td>
      </tr>
  
</table>
</div>
<%= link_to 'Back', skills_path %>