config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :skills
  resources :projects
  resources :users
  resources :project_users

  root 'welcome#index'

end

app/models/project.rb
class Project < ApplicationRecord
	has_and_belongs_to_many :skills
	has_many :project_users
	has_many :users, through: :project_users
	validates :name, length: { minimum: 2 }
  validates :start_date, :completion_date, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :admin_user,     only: [:new, :create, :edit, :update, :index, :destroy]
  def index
    @projects = Project.all
  end

  def new
  	@project = Project.new
    @skills = Skill.all
  end

  def create
  	@project = Project.new(project_params)
  	if @project.save
      redirect_to :action => 'new'
    else
      flash[:error] =  @project.errors.full_messages.join(', ')
      redirect_to :action => 'new'
    end
  end

	def edit
  	@project = Project.find(params[:id])
    @skills = Skill.all
	end

  def update
  	@project = Project.find(params[:id])
  	if @project.update(project_params)
  		redirect_to @project
  	else
  		render 'edit'
  	end
 	end

  def show
  	@project = Project.find(params[:id])
    @array = @project.project_users.map(&:user_id)
  end

  def destroy
    Project.find(params[:id]).destroy
   flash[:success] = "Project deleted"
    redirect_to projects_url
  end

  private
  def project_params
    params.require(:project).permit(:name, :start_date, :completion_date,:skill_ids => [])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<% @page_title = "Project" %>
<div class="project">
  <h1>Project input</h1>
  <%= form_for(@project) do |f| %>
    <p> Project:</br> <%= f.text_field :name%> </p>
    <div class="field">
      <%= collection_check_boxes(:project, :skill_ids , @skills, :id, :skill) %>
    </div>
    <p> Start Date:</br> <%= f.text_field :start_date%> </p>
    <p> End Date:</br> <%= f.text_field :completion_date%> </p>
    <%= f.submit "Submit" %>
   <% end %>




   <% if @project.errors.any? %>
    <ul class="Project_Errors">
    <% for message_error in @project.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1> Edit Form </h1>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<table>
  <tr>
    <th>Projects</th>


    <th colspan="2"></th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.skills.map {|s| s.skill}.join(', ') %></td>
      <td><%= link_to "Show", project_path(project)  %></td>
      <td><%= link_to "Edit",edit_project_path(project) %></td>
      <td><%= link_to 'Delete', project ,method: :delete,data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to "Create new project", {controller: 'projects', action: 'new'} %>
<br>
<%= link_to "Back", current_user %>

app/views/projects/new.html.erb
<% @page_title = "Project" %>
<%= render 'form' %>
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<% @page_title = "Project list" %>
 <div class="Project">
  <table>
  <tr>
    <th>Name</th>
    <th>Skill</th>
    <th>Start Date</th>
    <th>Completion Date</th>
    <th>User</th>
    <th colspan="2"></th>
  </tr>
    <tr>
      <td><%= @project.name %></td>
      <td><%= @project.skills.map {|c| c.skill}.join(', ') %></td>
      <td><%= @project.start_date %></td>
      <td><%= @project.completion_date %></td>
      <td><% @array.each do |id| %>
            <%= User.find(id).name %>  
          <% end %></td>
    </tr>

</table>
</div>

<%= link_to 'Assign User', new_project_user_path( :project_id => @project.id) %>
<%= link_to 'Back', projects_path %>