config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :skills
  resources :projects
  resources :users
  resources :project_users

  root 'welcome#index'

end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :user_id, :uniqueness => { :scope => :project_id }
end

app/controllers/project_users_controller.rb
class ProjectUsersController < ApplicationController
  before_action :admin_user,     only: [:new, :create,:edit, :index, :destroy, :show]
	before_action :current_project, only: [:new, :create]

	def index
    @assign_users = ProjectUser.all
  end

  def new
  	@assign_user = ProjectUser.new
 	end

 	def create
 		@assign_user = ProjectUser.new(assign_user_params)
    if @assign_user.save
      redirect_to @assign_user
    else
    	render 'new'
    end
  end

  def show
  	@assign_user = ProjectUser.find(params[:id])
  end

	def edit
	  @assign_user = ProjectUser.find(params[:id])
		@current_project = @assign_user.project
	end

	def update
	  @assign_user = ProjectUser.find(params[:id])
		@current_project = @assign_user.project
	  if @assign_user.update_attributes(assign_user_params)
	  	redirect_to @assign_user
	  else
	   	render 'edit'
	  end
	end

  def destroy
    ProjectUser.find(params[:id]).destroy
    flash[:success] = "Project unassigned"
    redirect_to project_users_path
  end

  private
	def assign_user_params
	  params.require(:project_user).permit(:user_id,:project_id)
	end

	def current_project
		@current_project = Project.find(params[:project_id])
	end
end

app/helpers/project_users_helper.rb
module ProjectUsersHelper
end

app/views/project_users/_form.html.erb
<%= form_for(@assign_user) do |f| %>
  <% if @assign_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assign_user.errors.count, "error") %> prohibited this project from being assigned:</h2>
      <ul>
      <% @assign_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.select :project_id , Project.all.collect{ |p| [ p.name, p.id ] if @current_project.id == p.id }.compact %>
  <%= f.select :user_id, User.all.collect { |p| [ p.name, p.id ] if @current_project.skills.index{ |x| !p.skills.include?(x)}.nil?}.compact %>
  <%= hidden_field_tag :project_id, @current_project.id %>
  <%= f.submit "Assign project" %>

<% end %>

app/views/project_users/edit.html.erb
<h1>Editing assigned_project</h1>
<%= form_for(@assign_user) do |f| %>
  <% if @assign_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assign_user.errors.count, "error") %> prohibited this project from being assigned:</h2>
      <ul>
      <% @assign_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.select :project_id , Project.all.collect{ |p| [ p.name, p.id ] if @current_project.id == p.id }%>
  <%= f.select :user_id, User.all.collect { |p| [ p.name, p.id ] if @current_project.skills.index{ |x| !p.skills.include?(x)}.nil? } %>

  <%= f.submit %>

<% end %>

<%= link_to 'Show', @assign_user %>



<%= link_to 'Back', project_users_path %>

app/views/project_users/index.html.erb
<h1>Listing assignedusers</h1>
<table>
  <tr>
    <th>Project</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assign_users.each do |assigneduser| %>
  <tr>
    <td><%= assigneduser.project.name %></td>
    <td><%= assigneduser.user.name %></td>
    <td><%= link_to "Edit",edit_project_user_path(assigneduser) %></td>
    <td><%= link_to 'Destroy', assigneduser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'Assign user to project', projects_path %>
<%= link_to "Back", current_user %>

app/views/project_users/new.html.erb
<h1>New assigned_project</h1>
<%= render 'form' %>


<%= link_to 'Back', project_users_path %>

app/views/project_users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Project:</b>
  <%= @assign_user.project.name %>
</p>
<p>
  <b>User:</b>
  <%= @assign_user.user.name %>
</p>


<%= link_to 'Edit', edit_project_user_path(@assign_user) %>
<%= link_to 'Back', project_users_path %>